<?php

namespace meh\batiInterimBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChefchantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChefchantierRepository extends EntityRepository
{
}
